Reward And Recognition System 2.0/force-app/main/default/objects/Feedback__c/Feedback__c.object-meta.xml
<CustomObject>
    <label>Feedback</label>
    <nameField>
        <displayFormat>EF-{0000}</displayFormat>
        <label>Received Feedback Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Feedbacks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Reward And Recognition System 2.0/force-app/main/default/objects/Feedback__c/fields/System_Configuration__c.field-meta.xml
<CustomField>
    <fullName>System_Configuration__c</fullName>
    <label>System Configuration</label>
    <referenceTo>System_Configuration__c</referenceTo>
    <relationshipLabel>Feedbacks</relationshipLabel>
    <relationshipName>Feedbacks</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Reward And Recognition System 2.0/force-app/main/default/objects/System_Configuration__c/System_Configuration__c.object-meta.xml
<CustomObject>
    <label>System Configuration</label>
    <nameField>
        <label>System Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>System Configuration</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Reward And Recognition System 2.0/force-app/main/default/classes/PointsTriggerDomain.cls
public class PointsTriggerDomain extends fflib_SObjectDomain {
    List<System_Configuration__c> configList = [SELECT Name, Points__c FROM System_Configuration__c];
    List<Feedback__c> newFeedbackList = new List<Feedback__c>();
    
    public PointsTriggerDomain(List<Feedback__c> sObjectList) {
        super(sObjectList);  
    }
    
    public class Constructor implements fflib_SObjectDomain.IConstructable {
        public fflib_SObjectDomain construct(List<SObject> sObjectList) {
            return new PointsTriggerDomain(sObjectList);
        }
    }
    public override void onBeforeInsert(){
        for (Feedback__c rf : (List<Feedback__c>)Trigger.new) {
            if (rf.System_Configuration__c == null) {
                rf.addError('System Configuration is required.' + rf.System_Configuration__r.Name);
            }
            else {
                for (System_Configuration__c configuration : configList) {
                    if (rf.System_Configuration__c == configuration.Id) {
                        try {
                            Decimal rating = (Decimal)rf.Rating__c;
                            Decimal points = configuration.Points__c;
                            if (rating != null && points != null) {
                                rf.Points__c = rating * points;
                            } else {
                                rf.addError('System Configuration not found.' + configuration.Name );
                            }
                        } catch (Exception ex) {
                            rf.addError('For this object, the system configuration is not available: ' + ex.getMessage());
                        }
                    }
                }
            }
        } 
    }
    
    public override void onBeforeUpdate(Map<Id,SObject> existingRecords){
                for (Feedback__c rf : (List<Feedback__c>)Trigger.new) {
            if (rf.System_Configuration__c == null) {
                rf.addError('System Configuration is required.' + rf.System_Configuration__r.Name);
            }
            else {
                for (System_Configuration__c configuration : configList) {
                    if (rf.System_Configuration__c == configuration.Id) {
                        try {
                            Decimal rating = (Decimal)rf.Rating__c;
                            Decimal points = configuration.Points__c;
                            if (rating != null && points != null) {
                                rf.Points__c = rating * points;
                            } else {
                                rf.addError('System Configuration not found.' + configuration.Name );
                            }
                        } catch (Exception ex) {
                            rf.addError('For this object, the system configuration is not available: ' + ex.getMessage());
                        }
                    }
                }
            }
        } 
    }
}