Reward And Recognition System 2.0/force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Empolyee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Reward And Recognition System 2.0/force-app/main/default/objects/Employee_Badge__c/Employee_Badge__c.object-meta.xml
<CustomObject>
    <label>Employee Badge</label>
    <nameField>
        <displayFormat>Emp Badge-{0000}</displayFormat>
        <label>Employee Badge  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employee Badges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Reward And Recognition System 2.0/force-app/main/default/objects/Employee_Badge__c/fields/Assigned_Badge__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Badge__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned Badge</label>
    <referenceTo>Badge_Configuration__c</referenceTo>
    <relationshipLabel>Employee Badges (Approved_Badge)</relationshipLabel>
    <relationshipName>Employee_Badges1</relationshipName>
    <type>Lookup</type>
</CustomField>

Reward And Recognition System 2.0/force-app/main/default/objects/Employee_Badge__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Category</label>
    <referenceTo>Category__c</referenceTo>
    <relationshipLabel>Employee Badges</relationshipLabel>
    <relationshipName>Employee_Badges</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Reward And Recognition System 2.0/force-app/main/default/objects/Employee_Badge__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Employee Badges</relationshipLabel>
    <relationshipName>Employee_Badges</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Reward And Recognition System 2.0/force-app/main/default/objects/Super_Badge_Configuration__c/Super_Badge_Configuration__c.object-meta.xml
<CustomObject>
    <label>Super Badge Configuration</label>
    <nameField>
        <label>Super Badge Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Super Badge Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Reward And Recognition System 2.0/force-app/main/default/objects/Super_Badge_Configuration__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Category</label>
    <referenceTo>Category__c</referenceTo>
    <relationshipLabel>Super Badge Configurations</relationshipLabel>
    <relationshipName>Super_Badge_Configurations</relationshipName>
    <type>Lookup</type>
</CustomField>

Reward And Recognition System 2.0/force-app/main/default/objects/Super_Badge_Configuration__c/fields/Required_Badge__c.field-meta.xml
<CustomField>
    <fullName>Required_Badge__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Required Badge</label>
    <referenceTo>Badge_Configuration__c</referenceTo>
    <relationshipLabel>Super Badge Configurations</relationshipLabel>
    <relationshipName>Super_Badge_Configurations</relationshipName>
    <type>Lookup</type>
</CustomField>

Reward And Recognition System 2.0/force-app/main/default/objects/Super_Badge_Configuration__c/fields/Super_Badge_Image__c.field-meta.xml
<CustomField>
    <fullName>Super_Badge_Image__c</fullName>
    <label>Super Badge Image</label>
    <type>Url</type>
</CustomField>

Reward And Recognition System 2.0/force-app/main/default/classes/SuperBadgeTriggerDomain.cls
public class SuperBadgeTriggerDomain  extends fflib_SObjectDomain {
    Map<String,Super_Badge_Configuration__c> superBadgeMap= new Map<String,Super_Badge_Configuration__c>(); 
    List<Employee_Super_Badge__c> newList = new List<Employee_Super_Badge__c>();    
    
    public SuperBadgeTriggerDomain(List<Employee_Badge__c> sObjectList) {
        super(sObjectList);
        // Initialize superBadgeMap when constructing the domain
        for(Super_Badge_Configuration__c superBadge:[Select Name,Super_Badge_Image__c,Category__c,Required_Badge__c from Super_Badge_Configuration__c]){
            superBadgeMap.put(superBadge.Required_Badge__c,superBadge);
        } 
    }
    
    public class Constructor implements fflib_SObjectDomain.IConstructable {
        public fflib_SObjectDomain construct(List<SObject> sObjectList) {
            return new SuperBadgeTriggerDomain(sObjectList);
        }
    }
    
    public override void onAfterUpdate(Map<Id,SObject> existingRecords){
        for(Employee_Badge__c empBadge:(List<Employee_Badge__c>)Trigger.new){        
            Employee_Badge__c oldRecord=(Employee_Badge__c)existingRecords.get(empBadge.Id);
            if(empBadge.Assigned_Badge__c != NULL && empBadge.Assigned_Badge__c != oldRecord.Assigned_Badge__c){
                if(superBadgeMap.get(empBadge.Assigned_Badge__c)!=Null){
                    Employee_Super_Badge__c superBadge = new Employee_Super_Badge__c();
                    superBadge.Employee__c = empBadge.Employee__c;
                    superBadge.Category__c = empBadge.Category__c;
                    superBadge.Super_Badge_Configuration__c = superBadgeMap.get(empBadge.Assigned_Badge__c).Id;
                    newList.add(superBadge);
                }
            }       
        }
        if(newList!=null){
            insert newList;
        }
    }
}