Reward And Recognition System 2.0/force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Empolyee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Reward And Recognition System 2.0/force-app/main/default/objects/Employee__c/fields/Metacube_Employee_Id__c.field-meta.xml
<CustomField>
    <fullName>Metacube_Employee_Id__c</fullName>
    <label>Metacube Employee Id</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

Reward And Recognition System 2.0/force-app/main/default/objects/Feedback__c/Feedback__c.object-meta.xml
<CustomObject>
    <label>Feedback</label>
    <nameField>
        <displayFormat>EF-{0000}</displayFormat>
        <label>Received Feedback Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Feedbacks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Reward And Recognition System 2.0/force-app/main/default/objects/Feedback__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipName>Received_Feedbacks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Reward And Recognition System 2.0/force-app/main/default/objects/Feedback__c/fields/Quarter__c.field-meta.xml
<CustomField>
    <fullName>Quarter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quarter</label>
    <referenceTo>Quarter__c</referenceTo>
    <relationshipName>Received_Feedbacks</relationshipName>
    <type>Lookup</type>
</CustomField>

Reward And Recognition System 2.0/force-app/main/default/objects/Quarter__c/Quarter__c.object-meta.xml
<CustomObject>
    <label>Quarter</label>
    <nameField>
        <label>Quarter Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quarters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Reward And Recognition System 2.0/force-app/main/default/objects/Received_Feedback__c/Received_Feedback__c.object-meta.xml
<CustomObject>
    <label>Received Feedback</label>
    <nameField>
        <displayFormat>EF-{0000}</displayFormat>
        <label>Received Feedback Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Received Feedbacks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Reward And Recognition System 2.0/force-app/main/default/objects/Received_Feedback__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Category</label>
    <referenceTo>Category__c</referenceTo>
    <relationshipLabel>Received Feedbacks</relationshipLabel>
    <relationshipName>Received_Feedbacks</relationshipName>
    <type>Lookup</type>
</CustomField>

Reward And Recognition System 2.0/force-app/main/default/objects/Received_Feedback__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Received Feedbacks</relationshipLabel>
    <relationshipName>Received_Feedbacks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Reward And Recognition System 2.0/force-app/main/default/objects/Received_Feedback__c/fields/Quarter__c.field-meta.xml
<CustomField>
    <fullName>Quarter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quarter</label>
    <referenceTo>Quarter__c</referenceTo>
    <relationshipLabel>Received Feedbacks</relationshipLabel>
    <relationshipName>Received_Feedbacks</relationshipName>
    <type>Lookup</type>
</CustomField>

Reward And Recognition System 2.0/force-app/main/default/objects/Received_Feedback__c/fields/Sub_Category__c.field-meta.xml
<CustomField>
    <fullName>Sub_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sub Category</label>
    <referenceTo>Sub_Category__c</referenceTo>
    <relationshipLabel>Received Feedbacks</relationshipLabel>
    <relationshipName>Received_Feedbacks</relationshipName>
    <type>Lookup</type>
</CustomField>

Reward And Recognition System 2.0/force-app/main/default/objects/Received_Feedback__c/fields/System__c.field-meta.xml
<CustomField>
    <fullName>System__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>System</label>
    <referenceTo>System__c</referenceTo>
    <relationshipLabel>Received Feedbacks</relationshipLabel>
    <relationshipName>Received_Feedbacks</relationshipName>
    <type>Lookup</type>
</CustomField>

Reward And Recognition System 2.0/force-app/main/default/objects/Sub_Category__c/Sub_Category__c.object-meta.xml
<CustomObject>
    <label>Sub Category</label>
    <nameField>
        <label>Sub Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub Categories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Reward And Recognition System 2.0/force-app/main/default/objects/Sub_Category__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <referenceTo>Category__c</referenceTo>
    <relationshipName>SubCategories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Reward And Recognition System 2.0/force-app/main/default/objects/System__c/System__c.object-meta.xml
<CustomObject>
    <label>System</label>
    <nameField>
        <label>System Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Systems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Reward And Recognition System 2.0/force-app/main/default/classes/RestApiClass.cls
@RestResource(urlMapping='/Feedback__c/')
global with sharing class RestApiClass {

//    @HttpPost
//     global static String insertAllData(String name,String quarter,String systems,String rating , String description, String metacubeId,String category,String subCategory) {
//         insertEmployee(name,metacubeId);
//         insertCategory(category);
//         insertSubCategory(subCategory,category);
//         insertQuarter(quarter);
//         insertSystem(systems);
//         insertReceivedFeedback(name,quarter,systems,rating ,description,metacubeId,category,subCategory);
//         return 'success ';
//     }

//      public static void insertEmployee(String name , String metacubeId){
//         List<Employee__c> employeeList=[select Name,Metacube_Employee_Id__c from Employee__c ];
//         List<String> EmployeeIdList=new List<String>();
//         for(Employee__c emp:employeeList){
//             EmployeeIdList.add(emp.metacube_Employee_Id__c);
//         }
//         String employeeIdString=String.join(EmployeeIdList,',');
//         if(!employeeIdString.contains(metacubeId)) {
//             Employee__c employee=new Employee__c(Name=name,Metacube_Employee_Id__c=metacubeId, Is_Active__c=true );
//             insert employee;
//         }
//      }

//     public static void insertCategory(String category){
//         List<Category__c> categoryList=[select Name from Category__c];
//         List<String> categoryNameList=new List<String>();
//         for(Category__c ct:categoryList){
//             categoryNameList.add(ct.Name);
//         }
//         if(!categoryNameList.contains(category)) {

//             Category__c newCategory=new Category__c(Name=category);
//             insert newCategory;
//         }
//      }

//      public static void insertSubCategory(String subCategory, String category ){
//         List<Sub_Category__c> subCategoryList=[select Name from Sub_Category__c];
//         List<String> subCategoryNameList=new List<String>();
//         for(Sub_Category__c ct:subCategoryList){
//             subCategoryNameList.add(ct.Name);
//         }
//         if(!subCategoryNameList.contains(subCategory)) {
//             Id catId=[select name from category__c where name like :category].get(0).id;
//             Sub_Category__c newSubCategory=new Sub_Category__c(Name=subCategory,category__c=catId);
//             insert newSubCategory;
//         }
//      }

//     public static void insertQuarter(String quarter){
//         List<Quarter__c> quarterList=[select Name from Quarter__c];
//         List<String> quarterNameList=new List<String>();
//         for(Quarter__c ct:quarterList){
//             quarterNameList.add(ct.Name);
//         }
//         if(!quarterNameList.contains(quarter)) {
//             Quarter__c newQuarter=new Quarter__c(Name=quarter);
//             insert newQuarter;
//         }
//      }

//     public static void insertSystem(String systems){
//         List<System__c> systemList=[select Name from System__c];
//         List<String> systemNameList=new List<String>();
//         for(System__c ct:systemList){
//             systemNameList.add(ct.Name);
//         }
//         if(!systemNameList.contains(systems)){
//             System__c newQuarter=new System__c(Name=systems);
//             insert newQuarter;
//         }
//      }


//     public static void insertReceivedFeedback(String name,String quarter,String systems,String rating , String description, String metacubeId,String category,String subCategory){

//         Id catId = [select name from Category__c where name like:category].get(0).Id;
//         Id subCatId = [select name from Sub_Category__c where name like:subCategory].get(0).Id;
//         Id sysId= [select name from system__c where name like:systems].get(0).Id;
//         Id empId = [select name from Employee__c where Metacube_Employee_Id__c like: metacubeId ].get(0).Id;
//         Id quarterID = [select name from Quarter__c where name like:quarter].get(0).Id;

//         Received_Feedback__c newFeedback = new Received_Feedback__c();
//         newFeedback.Rating__c=Integer.valueOf(rating);
//         newFeedback.Date__c=Date.today();
//         newFeedback.Description__c=description;
//         newFeedback.Category__c=catId;
//         newFeedback.Sub_Category__c=subCatId;
//         newFeedback.System__c=sysId;
//         newfeedback.Quarter__c=quarterID;
//         newFeedback.Employee__c=empId;
//         insert newfeedback;



//    }
//     @HttpGet
//     global static List<Received_Feedback__c> getFeedback() {
//         return [SELECT Id, Rating__c, description__c, Metacube_Employee_Id__c,Category__c,Sub_Category__c FROM Received_Feedback__c];
//     }


}