Reward And Recognition System 2.0/force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Empolyee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Reward And Recognition System 2.0/force-app/main/default/objects/Employee__c/fields/Employee_Id__c.field-meta.xml
<CustomField>
    <fullName>Employee_Id__c</fullName>
    <label>Employee Id</label>
    <length>250</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Reward And Recognition System 2.0/force-app/main/default/objects/Employee__c/fields/Monetization_Points__c.field-meta.xml
<CustomField>
    <fullName>Monetization_Points__c</fullName>
    <formula>Roll_Up_Total_Points__c-Roll_Up_Employee_Reward__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Monetization Points</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Reward And Recognition System 2.0/force-app/main/default/objects/Employee__c/fields/Roll_Up_Employee_Reward__c.field-meta.xml
<CustomField>
    <fullName>Roll_Up_Employee_Reward__c</fullName>
    <label>Roll Up Employee Reward</label>
    <summarizedField>Employee_Reward__c.Points_Redeemed__c</summarizedField>
    <summaryForeignKey>Employee_Reward__c.Employee__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

Reward And Recognition System 2.0/force-app/main/default/objects/Employee__c/fields/Roll_Up_Total_Points__c.field-meta.xml
<CustomField>
    <fullName>Roll_Up_Total_Points__c</fullName>
    <label>Roll Up Total Points</label>
    <summarizedField>Employee_Badge__c.Total_Points__c</summarizedField>
    <summaryForeignKey>Employee_Badge__c.Employee__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

Reward And Recognition System 2.0/force-app/main/default/classes/SelectorForEmployee.cls
public class SelectorForEmployee {
    public string objectName='Employee__c ';
    public String fieldName='Name,Email__c,Designation__c ,Employee_Id__c,Roll_Up_Total_Points__c,Monetization_Points__c,Roll_Up_Employee_Reward__c';
    
    public List<Employee__c> getEmployee(String EmployeeId){   
            String query=String.format('select {0} from {1} where id= :EmployeeId',
                                   new List<String> {fieldName,objectName});
        return  Database.query(query);
    }
    
      public List<Employee__c> getEmployee(){   
            String query=String.format('select {0} from {1} ',
                                   new List<String> {fieldName,objectName});
        return  Database.query(query);
    }
    
}