Reward And Recognition System 2.0/force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Empolyee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Reward And Recognition System 2.0/force-app/main/default/objects/Employee__c/fields/Employee_Id__c.field-meta.xml
<CustomField>
    <fullName>Employee_Id__c</fullName>
    <label>Employee Id</label>
    <length>250</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Reward And Recognition System 2.0/force-app/main/default/objects/Employee__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>First Name</label>
    <length>250</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Reward And Recognition System 2.0/force-app/main/default/classes/RRDeactivateEmployee.cls
@RestResource(urlMapping='/DeactivateEmployee/')
global class RRDeactivateEmployee {
    
     @HttpPost
    global static String DeactivateEmployee(List<EmployeeDetails> data){
        List<Employee__c> updateEmployeeList=new List<Employee__c>();
        Map<String,Employee__c>employeeMap=new Map<String,Employee__c>();
        
        SelectorForEmployeeAPI empList=new SelectorForEmployeeAPI();
        
         for(Employee__c emp: empList.getEmployee() ){
            employeeMap.put(emp.Employee_Id__c,emp);
        }
        
        //for(Employee__c emp:[select Employee_Id__c,Is_Active__c,First_Name__c,Last_Name__c from Employee__c]){
          //  employeeMap.put(emp.Employee_Id__c,emp);
        //}
        for(EmployeeDetails employee:data){
            if(employeeMap.keySet().contains(employee.employeeId)){
                employee__c updateEmployee=employeeMap.get(employee.employeeId);
                //if(employee.status.toLowerCase()!='active')
                updateEmployee.Is_Active__c=false;
                updateEmployeeList.add(updateEmployee);
            }
        }
        update(updateEmployeeList);  
        return 'Success';   
    }
    
    global class EmployeeDetails{
        public String employeeId {get;set;}
    }
}