Reward And Recognition System 2.0/force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Empolyee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Reward And Recognition System 2.0/force-app/main/default/objects/Employee__c/fields/Employee_Id__c.field-meta.xml
<CustomField>
    <fullName>Employee_Id__c</fullName>
    <label>Employee Id</label>
    <length>250</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Reward And Recognition System 2.0/force-app/main/default/objects/Employee__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>First Name</label>
    <length>250</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Reward And Recognition System 2.0/force-app/main/default/classes/SelectorForEmployeeAPI.cls
public class SelectorForEmployeeAPI extends fflib_SObjectSelector {

     public Schema.SObjectType getSObjectType(){
        return 	Employee__c.SObjectType;    
    }
    
    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField> {
            Employee__c.Name,
            Employee__c.First_Name__c,
            Employee__c.Last_Name__c,
            Employee__c.Email__c,
            Employee__c.Employee_Id__c
        };
    }
    
    public List<Employee__c> getEmployee(){
        
        String query=String.format('select {0} from {1}',
                                   new List<String> {getFieldListString(),getSObjectName()});
        
        return (List<Employee__c>) Database.query(query);
    }
}