Reward And Recognition System 2.0/force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Empolyee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Reward And Recognition System 2.0/force-app/main/default/objects/Employee_Reward__c/Employee_Reward__c.object-meta.xml
<CustomObject>
    <label>Employee Reward</label>
    <nameField>
        <label>Employee Reward Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employee Rewards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Reward And Recognition System 2.0/force-app/main/default/objects/Employee_Reward__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>Date Earned</label>
    <type>Date</type>
</CustomField>

Reward And Recognition System 2.0/force-app/main/default/objects/Employee_Reward__c/fields/Earned_Reward__c.field-meta.xml
<CustomField>
    <fullName>Earned_Reward__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Earned Reward</label>
    <referenceTo>Reward_Configuration__c</referenceTo>
    <relationshipLabel>Employee Rewards</relationshipLabel>
    <relationshipName>Employee_Rewards</relationshipName>
    <type>Lookup</type>
</CustomField>

Reward And Recognition System 2.0/force-app/main/default/objects/Employee_Reward__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipName>Employee_Rewards</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Reward And Recognition System 2.0/force-app/main/default/objects/Employee_Reward__c/fields/Points_Redeemed__c.field-meta.xml
<CustomField>
    <fullName>Points_Redeemed__c</fullName>
    <label>Points Redeemed</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Reward And Recognition System 2.0/force-app/main/default/objects/Reward_Configuration__c/Reward_Configuration__c.object-meta.xml
<CustomObject>
    <label>Reward Configuration</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reward Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Reward And Recognition System 2.0/force-app/main/default/objects/Reward_Configuration__c/fields/Reward_Image__c.field-meta.xml
<CustomField>
    <fullName>Reward_Image__c</fullName>
    <label>Reward Image</label>
    <type>Url</type>
</CustomField>

Reward And Recognition System 2.0/force-app/main/default/classes/SelectorForEmployeeReward.cls
public class SelectorForEmployeeReward {
public string objectName='Employee_Reward__c ';
    public String fieldName='Name,Employee__r.Name,Date__c ,Earned_Reward__r.Name,Earned_Reward__r.Reward_Image__c,Points_Redeemed__c,Status__c';
    
    
    public List<Employee_Reward__c > getEmployeeRewardHistory(String employeeId){   
        String query=String.format('select {0} from {1} where Employee__c =:employeeId Order By Date__c DESC',
                                   new List<String> {fieldName,objectName});
        return  Database.query(query);
    }
}