Reward And Recognition System 2.0/force-app/main/default/objects/Reward_Configuration__c/Reward_Configuration__c.object-meta.xml
<CustomObject>
    <label>Reward Configuration</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reward Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Reward And Recognition System 2.0/force-app/main/default/objects/Reward_Configuration__c/fields/Required_Reward_Points__c.field-meta.xml
<CustomField>
    <fullName>Required_Reward_Points__c</fullName>
    <label>Required Reward Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Reward And Recognition System 2.0/force-app/main/default/objects/Reward_Configuration__c/fields/Reward_Image__c.field-meta.xml
<CustomField>
    <fullName>Reward_Image__c</fullName>
    <label>Reward Image</label>
    <type>Url</type>
</CustomField>

Reward And Recognition System 2.0/force-app/main/default/objects/Reward_Configuration__c/fields/Reward_Type__c.field-meta.xml
<CustomField>
    <fullName>Reward_Type__c</fullName>
    <label>Reward Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Amazon Voucher</fullName>
            </value>
            <value>
                <fullName>Merchandise</fullName>
            </value>
            <value>
                <fullName>Cash</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Reward And Recognition System 2.0/force-app/main/default/classes/SelectorForRewardConfiguration.cls
public class SelectorForRewardConfiguration {
    public string objectName='Reward_Configuration__c ';
    public String fieldName='Name ,Reward_Image__c,Required_Reward_Points__c,Reward_Type__c';
    
    public List<Reward_Configuration__c> getRewardConfig(){   
        String query=String.format('select {0} from {1} ',
                                   new List<String> {fieldName,objectName});
        return  Database.query(query);
    }
}