Reward And Recognition System 2.0/force-app/main/default/objects/Employee_Badge__c/Employee_Badge__c.object-meta.xml
<CustomObject>
    <label>Employee Badge</label>
    <nameField>
        <displayFormat>Emp Badge-{0000}</displayFormat>
        <label>Employee Badge  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employee Badges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Reward And Recognition System 2.0/force-app/main/default/objects/Employee_Badge__c/fields/Assigned_Badge__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Badge__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned Badge</label>
    <referenceTo>Badge_Configuration__c</referenceTo>
    <relationshipLabel>Employee Badges (Approved_Badge)</relationshipLabel>
    <relationshipName>Employee_Badges1</relationshipName>
    <type>Lookup</type>
</CustomField>

Reward And Recognition System 2.0/force-app/main/default/objects/Employee_Badge__c/fields/Recommended_Badge__c.field-meta.xml
<CustomField>
    <fullName>Recommended_Badge__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Recommended Badge</label>
    <referenceTo>Badge_Configuration__c</referenceTo>
    <relationshipLabel>Employee Badges</relationshipLabel>
    <relationshipName>Employee_Badges</relationshipName>
    <type>Lookup</type>
</CustomField>

Reward And Recognition System 2.0/force-app/main/default/objects/Employee_Badge__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Reward And Recognition System 2.0/force-app/main/default/classes/ApprovedBadgeDomain.cls
public class ApprovedBadgeDomain extends fflib_SObjectDomain {
    
    public ApprovedBadgeDomain(List<Employee_Badge__c> sObjectList) {
        super(sObjectList);
    }
    
    public class Constructor implements fflib_SObjectDomain.IConstructable {
        public fflib_SObjectDomain construct(List<SObject> sObjectList) {
            return new ApprovedBadgeDomain(sObjectList);
        }
    }
       
    // Logical code for Trigger 
    public override void onBeforeUpdate(Map<Id,SObject> existingRecords) {      
        List<Employee_badge__c> employeeBadgeList= new List<Employee_badge__c>();
        List<Employee_badge__c> enl = (List<Employee_badge__c>)trigger.new;
        for(Employee_Badge__c empBadge:enl){
            if(empBadge.Status__c=='Approved'){
                empBadge.Assigned_Badge__c=empBadge.Recommended_Badge__c;
                //empBadge.Recommended_Badge__c = NULL;
                employeeBadgeList.add(empBadge);
            }
            
        }
    }
    
}