Reward And Recognition System 2.0/force-app/main/default/objects/Sub_Category__c/Sub_Category__c.object-meta.xml
<CustomObject>
    <label>Sub Category</label>
    <nameField>
        <label>Sub Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub Categories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Reward And Recognition System 2.0/force-app/main/default/objects/Sub_Category__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <referenceTo>Category__c</referenceTo>
    <relationshipName>SubCategories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Reward And Recognition System 2.0/force-app/main/default/objects/System__c/System__c.object-meta.xml
<CustomObject>
    <label>System</label>
    <nameField>
        <label>System Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Systems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Reward And Recognition System 2.0/force-app/main/default/objects/System_Configuration__c/System_Configuration__c.object-meta.xml
<CustomObject>
    <label>System Configuration</label>
    <nameField>
        <label>System Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>System Configuration</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Reward And Recognition System 2.0/force-app/main/default/objects/System_Configuration__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Category</label>
    <referenceTo>Category__c</referenceTo>
    <relationshipLabel>System_Configuration</relationshipLabel>
    <relationshipName>System_Configuration</relationshipName>
    <type>Lookup</type>
</CustomField>

Reward And Recognition System 2.0/force-app/main/default/objects/System_Configuration__c/fields/Sub_Category__c.field-meta.xml
<CustomField>
    <fullName>Sub_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sub Category</label>
    <referenceTo>Sub_Category__c</referenceTo>
    <relationshipLabel>System_Configuration</relationshipLabel>
    <relationshipName>System_Configuration</relationshipName>
    <type>Lookup</type>
</CustomField>

Reward And Recognition System 2.0/force-app/main/default/objects/System_Configuration__c/fields/System__c.field-meta.xml
<CustomField>
    <fullName>System__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>System</label>
    <referenceTo>System__c</referenceTo>
    <relationshipLabel>System_Configuration</relationshipLabel>
    <relationshipName>System_Configuration</relationshipName>
    <type>Lookup</type>
</CustomField>

Reward And Recognition System 2.0/force-app/main/default/classes/SelectorForSystemConfiguration.cls
public class SelectorForSystemConfiguration  {
 public string objectName='System_Configuration__c';
    public String fieldName='Name,Category__r.Name,Sub_Category__r.Name,System__r.Name,Points__c';
    //public Schema.SObjectType getSObjectType(){
      //  return 	System_Configuration__c.SObjectType;    
   // }
    /*
    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField> {
            System_Configuration__c.Name,
            System_Configuration__c.Category__r.Name, 
            System_Configuration__c.Sub_Category__r.Name,
            System_Configuration__c.System__r.Name,
            System_Configuration__c.Points__c
     		};
    }
*/
    
    public List<System_Configuration__c> getSystemConfiguration(){
        
        String query=String.format('select {0} from {1}',
                                   new List<String> {fieldName,objectName});
        
        return  Database.query(query);
    }
}