Reward And Recognition System 2.0/force-app/main/default/objects/Sub_Category__c/Sub_Category__c.object-meta.xml
<CustomObject>
    <label>Sub Category</label>
    <nameField>
        <label>Sub Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub Categories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Reward And Recognition System 2.0/force-app/main/default/objects/Sub_Category__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <referenceTo>Category__c</referenceTo>
    <relationshipName>SubCategories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Reward And Recognition System 2.0/force-app/main/default/classes/SelectorForSubCategory.cls
public class SelectorForSubCategory extends fflib_SObjectSelector {

     public Schema.SObjectType getSObjectType(){
        return 	Sub_Category__c.SObjectType;    
    }
    
    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField> {
            Sub_Category__c.Name};
    }
    
    public List<Sub_Category__c> getSubCategory(String categoryValue){
        String query=String.format('select {0} from {1} where Category__r.name like: categoryValue',
                                   new List<String> {getFieldListString(),getSObjectName()});   
        return (List<Sub_Category__c>) Database.query(query);
    }
    
       public List<Sub_Category__c> getSubCategoryForRRAPI(){
        String query=String.format('select {0} from {1}',
                                   new List<String> {getFieldListString(),getSObjectName()}); 
        return (List<Sub_Category__c>) Database.query(query);
    }
}