Reward And Recognition System 2.0/force-app/main/default/objects/Employee_Reward__c/Employee_Reward__c.object-meta.xml
<CustomObject>
    <label>Employee Reward</label>
    <nameField>
        <label>Employee Reward Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employee Rewards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Reward And Recognition System 2.0/force-app/main/default/objects/Employee_Reward__c/fields/Earned_Reward__c.field-meta.xml
<CustomField>
    <fullName>Earned_Reward__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Earned Reward</label>
    <referenceTo>Reward_Configuration__c</referenceTo>
    <relationshipLabel>Employee Rewards</relationshipLabel>
    <relationshipName>Employee_Rewards</relationshipName>
    <type>Lookup</type>
</CustomField>

Reward And Recognition System 2.0/force-app/main/default/objects/Reward_Configuration__c/Reward_Configuration__c.object-meta.xml
<CustomObject>
    <label>Reward Configuration</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reward Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Reward And Recognition System 2.0/force-app/main/default/objects/Status_Tracking__c/Status_Tracking__c.object-meta.xml
<CustomObject>
    <label>Status Tracking</label>
    <nameField>
        <displayFormat>ST-{000000}</displayFormat>
        <label>Status Tracking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Status Tracking</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Reward And Recognition System 2.0/force-app/main/default/objects/Status_Tracking__c/fields/Employee_Reward__c.field-meta.xml
<CustomField>
    <fullName>Employee_Reward__c</fullName>
    <label>Employee Reward</label>
    <referenceTo>Employee_Reward__c</referenceTo>
    <relationshipLabel>Status Tracking</relationshipLabel>
    <relationshipName>Status_Tracking</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Reward And Recognition System 2.0/force-app/main/default/classes/SelectorForStatusTracking.cls
public class SelectorForStatusTracking {
    public string objectName='Status_Tracking__c';
    public String fieldName='Status__c,Processed_Date__c,Employee_Reward__r.Earned_Reward__r.Name';
    
    public List<Status_Tracking__c> getStatus(String rewardId){   
        String query=String.format('select {0} from {1} where Employee_reward__c =:rewardId order by Processed_Date__c DESC',
                                   new List<String> {fieldName,objectName});
        return  Database.query(query);
    }
}