Reward And Recognition System 2.0/force-app/main/default/objects/Badge_Configuration__c/Badge_Configuration__c.object-meta.xml
<CustomObject>
    <label>Badge Configuration</label>
    <nameField>
        <displayFormat>Badge-{00000}</displayFormat>
        <label>Badge Configuration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Badge Configurations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Reward And Recognition System 2.0/force-app/main/default/objects/Badge_Configuration__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <referenceTo>Category__c</referenceTo>
    <relationshipLabel>Badge Configurations</relationshipLabel>
    <relationshipName>Badge_Configurations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Reward And Recognition System 2.0/force-app/main/default/objects/Contact/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

Reward And Recognition System 2.0/force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Empolyee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Reward And Recognition System 2.0/force-app/main/default/objects/Employee__c/fields/Employee_Id__c.field-meta.xml
<CustomField>
    <fullName>Employee_Id__c</fullName>
    <label>Employee Id</label>
    <length>250</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Reward And Recognition System 2.0/force-app/main/default/objects/Employee_Badge__c/Employee_Badge__c.object-meta.xml
<CustomObject>
    <label>Employee Badge</label>
    <nameField>
        <displayFormat>Emp Badge-{0000}</displayFormat>
        <label>Employee Badge  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employee Badges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Reward And Recognition System 2.0/force-app/main/default/objects/Employee_Badge__c/fields/Assigned_Badge__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Badge__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned Badge</label>
    <referenceTo>Badge_Configuration__c</referenceTo>
    <relationshipLabel>Employee Badges (Approved_Badge)</relationshipLabel>
    <relationshipName>Employee_Badges1</relationshipName>
    <type>Lookup</type>
</CustomField>

Reward And Recognition System 2.0/force-app/main/default/objects/Employee_Badge__c/fields/Badge_Configuration__c.field-meta.xml
<CustomField>
    <fullName>Badge_Configuration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Badge Configuration</label>
    <referenceTo>Badge_Configuration__c</referenceTo>
    <relationshipLabel>Employee Badges</relationshipLabel>
    <relationshipName>Employee_Badges</relationshipName>
    <type>Lookup</type>
</CustomField>

Reward And Recognition System 2.0/force-app/main/default/objects/Employee_Badge__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Category</label>
    <referenceTo>Category__c</referenceTo>
    <relationshipLabel>Employee Badges</relationshipLabel>
    <relationshipName>Employee_Badges</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Reward And Recognition System 2.0/force-app/main/default/objects/Employee_Badge__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Employee Badges</relationshipLabel>
    <relationshipName>Employee_Badges</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Reward And Recognition System 2.0/force-app/main/default/objects/Employee_Badge__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Reward And Recognition System 2.0/force-app/main/default/objects/Employee_Reward__c/Employee_Reward__c.object-meta.xml
<CustomObject>
    <label>Employee Reward</label>
    <nameField>
        <label>Employee Reward Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employee Rewards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Reward And Recognition System 2.0/force-app/main/default/objects/Employee_Reward__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>Date Earned</label>
    <type>Date</type>
</CustomField>

Reward And Recognition System 2.0/force-app/main/default/objects/Employee_Reward__c/fields/Earned_Reward__c.field-meta.xml
<CustomField>
    <fullName>Earned_Reward__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Earned Reward</label>
    <referenceTo>Reward_Configuration__c</referenceTo>
    <relationshipLabel>Employee Rewards</relationshipLabel>
    <relationshipName>Employee_Rewards</relationshipName>
    <type>Lookup</type>
</CustomField>

Reward And Recognition System 2.0/force-app/main/default/objects/Employee_Reward__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipName>Employee_Rewards</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Reward And Recognition System 2.0/force-app/main/default/objects/Employee_Reward__c/fields/Points_Redeemed__c.field-meta.xml
<CustomField>
    <fullName>Points_Redeemed__c</fullName>
    <label>Points Redeemed</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Reward And Recognition System 2.0/force-app/main/default/objects/Reward_Configuration__c/Reward_Configuration__c.object-meta.xml
<CustomObject>
    <label>Reward Configuration</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reward Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Reward And Recognition System 2.0/force-app/main/default/objects/Reward_Configuration__c/fields/Reward_Image__c.field-meta.xml
<CustomField>
    <fullName>Reward_Image__c</fullName>
    <label>Reward Image</label>
    <type>Url</type>
</CustomField>

Reward And Recognition System 2.0/force-app/main/default/classes/EmployeeUnderBadge.cls
public class EmployeeUnderBadge {
    @AuraEnabled(Cacheable=true) 
    public static List<Employee_Badge__c> getEmployee(String badgeId){
        List <Employee_badge__c> badgeHoldersList=new List<Employee_Badge__c> ();
        SelectorForEmployeeBadge badgeHolderSelector=new SelectorForEmployeeBadge();
        badgeHoldersList=badgeHolderSelector.getBadgeHolder(badgeId);
        return badgeHoldersList;
        
        /*
        return [select Name, Category__r.Name ,Employee__r.Name,Employee__r.Employee_Id__c ,Total_Points__c,Assigned_Badge__r.Name from Employee_Badge__c
                where Assigned_Badge__c= :badgeId order by Total_Points__c DESC   ];
        */
    }
    
    @AuraEnabled(Cacheable=true)
    public static List<Badge_Configuration__c> getBadge(String currentBadgeId){
        
        SelectorForBadgeConfiguration BadgeConfigSelector=new SelectorForBadgeConfiguration();
        List<Badge_Configuration__c> badgeList= BadgeConfigSelector.getBadges(currentBadgeId);
        return badgeList;
        /*
        return [select Name ,Image__c, Category__r.Name from Badge_Configuration__c where Id=:currentBadgeId ];
        */
    }
    
    public static String getCurrentEmployee(){    
        /*
         User currentUser = [SELECT email,contactId,Contact.Name FROM User WHERE Id = :UserInfo.getUserId()].get(0); 
        */
        
        SelectorForUser userSelector=new SelectorForUser();
        User currentUser=userSelector.getUser(UserInfo.getUserId()).get(0);
        
        System.debug('the current user is '+currentUser);
        /*
        Contact currentContact=[SELECT Employee__c from Contact where Id=:currentUser.ContactId].get(0);
       */
        SelectorForContact contactSelector= new SelectorForContact();
        Contact currentContact= contactSelector.getContact((currentUser.ContactId)).get(0);
        System.debug('the current contact is '+currentContact);
        System.debug('the Employee Id is '+currentContact.Employee__c );
        return currentContact.Employee__c  ;
    }
    
    
    @AuraEnabled(Cacheable=true) 
    public static List<Employee_Reward__c> getRewardHistory(){
       String employeeId=getCurrentEmployee();
        System.debug('The Employee Id is '+employeeId);
        /*
        List<Employee_Reward__c> rewardHistory=  [select  Name,Employee__r.Name,Date__c ,Earned_Reward__r.Name,Earned_Reward__r.Reward_Image__c,Points_Redeemed__c,Status__c from Employee_Reward__c where Employee__c =:employeeId Order By Date__c DESC];
		*/
        SelectorForEmployeeReward employeeRewardSelector=new SelectorForEmployeeReward();
        List<Employee_Reward__c> rewardHistory= employeeRewardSelector.getEmployeeRewardHistory(employeeId);
        System.debug('the reward history is '+ rewardHistory);
        return  rewardHistory;
        
    }
    
    
}