Reward And Recognition System 2.0/force-app/main/default/objects/Badge_Configuration__c/Badge_Configuration__c.object-meta.xml
<CustomObject>
    <label>Badge Configuration</label>
    <nameField>
        <displayFormat>Badge-{00000}</displayFormat>
        <label>Badge Configuration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Badge Configurations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Reward And Recognition System 2.0/force-app/main/default/objects/Badge_Configuration__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <referenceTo>Category__c</referenceTo>
    <relationshipLabel>Badge Configurations</relationshipLabel>
    <relationshipName>Badge_Configurations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Reward And Recognition System 2.0/force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Empolyee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Reward And Recognition System 2.0/force-app/main/default/objects/Employee__c/fields/Employee_Id__c.field-meta.xml
<CustomField>
    <fullName>Employee_Id__c</fullName>
    <label>Employee Id</label>
    <length>250</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Reward And Recognition System 2.0/force-app/main/default/objects/Employee_Badge__c/Employee_Badge__c.object-meta.xml
<CustomObject>
    <label>Employee Badge</label>
    <nameField>
        <displayFormat>Emp Badge-{0000}</displayFormat>
        <label>Employee Badge  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employee Badges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Reward And Recognition System 2.0/force-app/main/default/objects/Employee_Badge__c/fields/Assigned_Badge__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Badge__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned Badge</label>
    <referenceTo>Badge_Configuration__c</referenceTo>
    <relationshipLabel>Employee Badges (Approved_Badge)</relationshipLabel>
    <relationshipName>Employee_Badges1</relationshipName>
    <type>Lookup</type>
</CustomField>

Reward And Recognition System 2.0/force-app/main/default/objects/Employee_Badge__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Category</label>
    <referenceTo>Category__c</referenceTo>
    <relationshipLabel>Employee Badges</relationshipLabel>
    <relationshipName>Employee_Badges</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Reward And Recognition System 2.0/force-app/main/default/objects/Employee_Badge__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Employee Badges</relationshipLabel>
    <relationshipName>Employee_Badges</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Reward And Recognition System 2.0/force-app/main/default/classes/RRGetBadgeDetailsAPI.cls
@RestResource(urlMapping='/GetBadgePointsDetails/')
global class RRGetBadgeDetailsAPI {

    @HttpGet
    global static List<EmployeeBadgeDetails> getBadge() {
        
        List<EmployeeBadgeDetails> getApiList=new List<EmployeeBadgeDetails>();
      List<Employee_Badge__c> employeeBadgeList=[SELECT Total_Points__c, Category__r.name,Employee__r.name ,Employee__r.Employee_Id__c,
                Assigned_Badge__r.title__c, Assigned_Badge__r.Image__c
                from Employee_Badge__c];
        
        for(Employee_Badge__c emp:employeeBadgeList){
           EmployeeBadgeDetails wrapperObj=new  EmployeeBadgeDetails();
			wrapperObj.category=emp.Category__r.name;
            wrapperObj.totalPoints=emp.Total_Points__c;
            wrapperObj.badgeTitle= emp.Assigned_Badge__r.title__c;
            wrapperObj.employeeId=emp.Employee__r.Employee_Id__c;
            wrapperObj.badgeImage=emp.Assigned_Badge__r.Image__c;
            wrapperObj.employeeName=emp.Employee__r.name;
            getApiList.add(wrapperObj);
        }
        return getApiList;
    }
    
    
    global class EmployeeBadgeDetails{  
        public String category { get; set; }
        public String badgeImage { get; set; }
        public String employeeId { get; set; }
        public String employeeName{get;set;}
        public String badgeTitle{get ;set;}
        public Decimal totalPoints{get;set;}
    }
}