Reward And Recognition System 2.0/force-app/main/default/objects/Badge_Configuration__c/Badge_Configuration__c.object-meta.xml
<CustomObject>
    <label>Badge Configuration</label>
    <nameField>
        <displayFormat>Badge-{00000}</displayFormat>
        <label>Badge Configuration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Badge Configurations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Reward And Recognition System 2.0/force-app/main/default/objects/Badge_Configuration__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <referenceTo>Category__c</referenceTo>
    <relationshipLabel>Badge Configurations</relationshipLabel>
    <relationshipName>Badge_Configurations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Reward And Recognition System 2.0/force-app/main/default/classes/SelectorForBadgeConfiguration.cls
public class SelectorForBadgeConfiguration {
    
    public string objectName='Badge_Configuration__c';
    public String fieldName='Name,Category__r.Name,Image__c';
    
    public List<Badge_Configuration__c> getBadges(){   
        String query=String.format('select {0} from {1}',
                                   new List<String> {fieldName,objectName});
        return  Database.query(query);
    }
    
    public List<Badge_Configuration__c> getBadges(String currentBadgeId){
         String query=String.format('select {0} from {1}  where Id=:currentBadgeId',
                                   new List<String> {fieldName,objectName});
        return  Database.query(query);
    }
    
    
}