Reward And Recognition System 2.0/force-app/main/default/objects/Badge_Configuration__c/Badge_Configuration__c.object-meta.xml
<CustomObject>
    <label>Badge Configuration</label>
    <nameField>
        <displayFormat>Badge-{00000}</displayFormat>
        <label>Badge Configuration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Badge Configurations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Reward And Recognition System 2.0/force-app/main/default/objects/Badge_Configuration__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <referenceTo>Category__c</referenceTo>
    <relationshipLabel>Badge Configurations</relationshipLabel>
    <relationshipName>Badge_Configurations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Reward And Recognition System 2.0/force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Empolyee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Reward And Recognition System 2.0/force-app/main/default/objects/Employee__c/fields/Employee_Id__c.field-meta.xml
<CustomField>
    <fullName>Employee_Id__c</fullName>
    <label>Employee Id</label>
    <length>250</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Reward And Recognition System 2.0/force-app/main/default/objects/Employee_Badge__c/Employee_Badge__c.object-meta.xml
<CustomObject>
    <label>Employee Badge</label>
    <nameField>
        <displayFormat>Emp Badge-{0000}</displayFormat>
        <label>Employee Badge  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employee Badges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Reward And Recognition System 2.0/force-app/main/default/objects/Employee_Badge__c/fields/Assigned_Badge__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Badge__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned Badge</label>
    <referenceTo>Badge_Configuration__c</referenceTo>
    <relationshipLabel>Employee Badges (Approved_Badge)</relationshipLabel>
    <relationshipName>Employee_Badges1</relationshipName>
    <type>Lookup</type>
</CustomField>

Reward And Recognition System 2.0/force-app/main/default/objects/Employee_Badge__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Category</label>
    <referenceTo>Category__c</referenceTo>
    <relationshipLabel>Employee Badges</relationshipLabel>
    <relationshipName>Employee_Badges</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Reward And Recognition System 2.0/force-app/main/default/objects/Employee_Badge__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Employee Badges</relationshipLabel>
    <relationshipName>Employee_Badges</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Reward And Recognition System 2.0/force-app/main/default/classes/SelectorForEmployeeBadge.cls
public class SelectorForEmployeeBadge {
    public string objectName='Employee_Badge__c ';
    public String fieldName='Name,Employee__r.Name,Category__r.Name,Assigned_Badge__r.Title__c,Assigned_Badge__r.Image__c,Employee__r.Employee_Id__c,Total_Points__c,Assigned_Badge__r.Name';
    
    public List<Employee_Badge__c> getEmployeeBadge(String EmployeeId){   
        String query=String.format('select {0} from {1} where Employee__c= :EmployeeId',
                                   new List<String> {fieldName,objectName});
        return  Database.query(query);
    }
    
    public List<Employee_Badge__c> getBadgeHolder(String badgeId){
                String query=String.format('select {0} from {1} where Assigned_Badge__c= :badgeId order by Total_Points__c DESC ',
                                   new List<String> {fieldName,objectName});
        return  Database.query(query);
    }
    
    public List<Employee_Badge__c> getEmployeeBadge(){
         String query=String.format('select {0} from {1} ',
                                   new List<String> {fieldName,objectName});
        return  Database.query(query);
    }
    
}