Reward And Recognition System 2.0/force-app/main/default/objects/Badge_Configuration__c/Badge_Configuration__c.object-meta.xml
<CustomObject>
    <label>Badge Configuration</label>
    <nameField>
        <displayFormat>Badge-{00000}</displayFormat>
        <label>Badge Configuration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Badge Configurations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Reward And Recognition System 2.0/force-app/main/default/objects/Badge_Configuration__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <referenceTo>Category__c</referenceTo>
    <relationshipLabel>Badge Configurations</relationshipLabel>
    <relationshipName>Badge_Configurations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Reward And Recognition System 2.0/force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Empolyee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Reward And Recognition System 2.0/force-app/main/default/objects/Employee_Badge__c/Employee_Badge__c.object-meta.xml
<CustomObject>
    <label>Employee Badge</label>
    <nameField>
        <displayFormat>Emp Badge-{0000}</displayFormat>
        <label>Employee Badge  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employee Badges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Reward And Recognition System 2.0/force-app/main/default/objects/Employee_Badge__c/fields/Assigned_Badge__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Badge__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned Badge</label>
    <referenceTo>Badge_Configuration__c</referenceTo>
    <relationshipLabel>Employee Badges (Approved_Badge)</relationshipLabel>
    <relationshipName>Employee_Badges1</relationshipName>
    <type>Lookup</type>
</CustomField>

Reward And Recognition System 2.0/force-app/main/default/objects/Employee_Badge__c/fields/Badge_Configuration__c.field-meta.xml
<CustomField>
    <fullName>Badge_Configuration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Badge Configuration</label>
    <referenceTo>Badge_Configuration__c</referenceTo>
    <relationshipLabel>Employee Badges</relationshipLabel>
    <relationshipName>Employee_Badges</relationshipName>
    <type>Lookup</type>
</CustomField>

Reward And Recognition System 2.0/force-app/main/default/objects/Employee_Badge__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Category</label>
    <referenceTo>Category__c</referenceTo>
    <relationshipLabel>Employee Badges</relationshipLabel>
    <relationshipName>Employee_Badges</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Reward And Recognition System 2.0/force-app/main/default/objects/Employee_Badge__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Employee Badges</relationshipLabel>
    <relationshipName>Employee_Badges</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Reward And Recognition System 2.0/force-app/main/default/classes/FetchEmployeeBadge.cls
public class FetchEmployeeBadge {

    @AuraEnabled(cacheable=true)
    public static List<Employee_Badge__c> fetchEmpBadge(Id employeeId){
        /*
        List<Employee_Badge__c> badges =[select Employee__r.Name,Category__r.Name,Assigned_Badge__r.Title__c,Assigned_Badge__r.Image__c from Employee_Badge__c where Employee__c=:EmployeeId];
       */
        
        SelectorforEmployeeBadge EmployeeBadgeSelector= new SelectorforEmployeeBadge();
        List<Employee_Badge__c> badges=EmployeeBadgeSelector.getEmployeeBadge(employeeId);
        List<Employee_Badge__c> filterList= new List<Employee_Badge__c>();
        for(Employee_Badge__c bg:badges){
            if(bg.Assigned_Badge__c!=Null){
                filterList.add(bg);
            }
        }
        return filterList;    
    }
    
   @AuraEnabled(cacheable=true)
    public static List<AggregateResult> fetchEmpInBadge(){
         return [SELECT Assigned_Badge__c,COUNT(Employee__c) employeeCount FROM Employee_Badge__c GROUP BY Assigned_Badge__c];
    }    

    @AuraEnabled(cacheable=true)
    public static List<Badge_Configuration__c> getBadges(){  
        SelectorForBadgeConfiguration badgeSelector=new SelectorForBadgeConfiguration();
        List<Badge_Configuration__c> badgeList=badgeSelector.getBadges();
        return badgeList;
        
        /*
        return [Select Name,Category__r.Name,Image__c from Badge_Configuration__c];
       */
    }

    @AuraEnabled(cacheable=true)
    public static List<Employee_Super_Badge__c> fetchEmpSuperBadge(Id employeeId){
        try {
            /*
            List<Employee_Super_Badge__c> superBadges = [Select Employee__r.Name,Category__r.Name, 
                                                         Super_Badge_Configuration__r.Name,
                                                         Super_Badge_Configuration__r.Super_Badge_Image__c
                                                         from Employee_Super_Badge__c 
                                                         where Employee__c=:EmployeeId];
            */
            SelectorForEmployeeSuperBadge employeeSuperBadgeSelector= new SelectorForEmployeeSuperBadge();
            List<Employee_Super_Badge__c> superBadges=employeeSuperBadgeSelector.getEmployeeSuperBadge(employeeId);
            return superBadges;
            
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}